### ISSUE TITLE
Parent/Child Management for Trello not working in chrome 59 version

### ISSUE THREAD

**Issue by pragnya20** [handsomecode/trello-parent-child#32] opened 2017-06-28 09:40 UTC
After installation of chrome 59, parent/child relationship not working in chrome 59 version. Unable to view the child cards and parent .

**Comment by skgchn** [comment] 2017-06-28 11:06
Does now work in Opera 46.0.2597.32 as well.

**Comment by guygadebois** [comment] 2017-06-28 14:01
Not working on Firefox neither since today. 
I'm using a `stylish` dark style for trello, and I noticed this morning that some of the trello classes had changed this morning, and my css theme was not working any more on cards.
So I guess there was a Trello update today that broke compatibility of the extension.

**Comment by guygadebois** [comment] 2017-06-28 14:03
This issue and https://github.com/handsomecode/trello-parent-child/issues/31 should be merged together as they're duplicate.

**Comment by alexzub** [comment] 2017-07-05 02:53
On it – will release a fix ASAP. Unfortunate timing with all the holidays.

**Comment by alexzub** [comment] 2017-07-06 13:26
This turns out to be Trello DOM change issue; hoping to release an official update during the day today.

Testers are welcome: https://github.com/handsomecode/trello-parent-child/commit/e88b7398970dc0a18f4d7d05f2c8a7d7143de6d6

**Comment by guygadebois** [comment] 2017-07-06 13:27
Gonna test on FF today

**Comment by guygadebois** [comment] 2017-07-06 13:51
Thanks for the fix @alexzub, I can confirm it works on Firefox. Here is the tests I've done:
- Create a link via the "Child" button
- Create a link via the "Parent" button
- Check existing links
- Remove a link via the "Parent" button

Everything seems back to normal! :+1:

**Closed as completed** 2017-07-06 15:19 UTC

**Comment by jessypants** [comment] 2017-07-06 16:37
I see that this issue is closed, but I'm still experiencing the issue in Chrome 59. The parent and child buttons aren't showing up at all.

**Comment by alexzub** [comment] 2017-07-06 16:46
@jessypants I've submitted the plugin to Chrome Store and it should get updated for everyone within a few hours. New version update # is 0.8.1. Unfortunately the update is not instant for everybody.

**Comment by jessypants** [comment] 2017-07-06 16:47
@alexzub Thanks for the update! I appreciate the fast response.

**Comment by Senthil-Manoharan** [comment] 2017-08-11 10:21
Hi,
I tried to add a child card, but couldn't.

Issue faced - Chrome Browser - Version 60.0.3112.90 (Official Build) (32-bit)

Note - Previously faced the same issue in Chrome version 59. Latter it got fixed and worked. Now i updated my Chrome version and again face the same problem.

Please kindly support.

Thank in advance
