### ISSUE TITLE
FEATURE REQUEST: Gantt Chart (or) project wide dependency visualization

### ISSUE THREAD

**Issue by dheerajbhaskar** [handsomecode/trello-parent-child#26] opened 2017-01-15 14:20 UTC
How about a gantt chart or a project wise dependency visualization

Something like:
![Gantt](https://cloud.githubusercontent.com/assets/19431375/15411892/a47d7f30-1e23-11e6-945d-3e3347f06c85.png)

**Comment by alexzub** [comment] 2017-01-15 21:13
@dheerajbhaskar **I'm closing this thread as it's a duplicate of this: https://github.com/handsomecode/trello-parent-child/issues/7**

I'd like to note that while we're considering adding this feature at some point, it is very much outside of the scope of a simple tool we've built and it's unlikely that we'll have this feature in the near future.

I'd recommend reaching out to [Trello Gantt Chart plugin developers](https://elegantt.com/) to explore the possibility of them integrating with the Parent/Child Management plugin.

Thank you!

**Closed as completed by alexzub** 2017-01-15 21:13 UTC
