### ISSUE TITLE
Hiccups - Blinking Checklist display on front of cards

### ISSUE THREAD

**Issue by mitzilla** [handsomecode/trello-parent-child#15] opened 2016-11-21 22:48 UTC
Once a card has children attached it begins blinking on and off the checklist and description symbols on the front of the card. 
- There is no checklist or description entered on the card.
- When I do enter a description and checklist it stops but it blinks an extra item in the checklist's count.

Chrome Version: 54.0.2840.98 (64-bit)
Mac Pro Late 2013

**Comment by mimkorn** [comment] 2016-12-14 22:34
I can confirm, this seems to be a bug. Now many of my cards are literally dancing. :/

Version 55.0.2883.87 m (64-bit)
Windows 10

**Comment by alexzub** [comment] 2016-12-14 23:47
@mitzilla @mimkorn 
1) try to use it in Incognito mode, having activated just the Parent/Child plugin there. Do you still experience the issue?
2) If the issue is gone, please list the plugins you have installed that interact with Trello.

Thanks!

**Comment by mimkorn** [comment] 2016-12-15 10:08
Hi, I tried the first suggested steps. I still experience the issue, even if this is the only activated extension. It might be useful to know that:
- This is the first time I am using the plugin, just found your product (it is amazing.. I just need it to work correctly :D )
- Also the "parent, child" buttons are not present immediately and the listings of the parents childs are not present immediately. Usually you have to wait a few seconds for them to appear.

**Comment by alexzub** [comment] 2016-12-15 14:39
@mimkorn There's an update coming in the next 4-5 days, it might get the issue fixed since some relevant parts of the code was rebuilt from scratch.

If that doesn't help, what would help us is access to a public board that has the issue. Let's get in touch after the update.

Thanks!

**Comment by mimkorn** [comment] 2016-12-15 14:55
@azmorf Ok, thanks, I will wait. Is there something I need to do to update the extension or does it update itself on the fly?

**Comment by mimkorn** [comment] 2016-12-20 19:52
Hi, any update on this? I still have the bug, still cannot use the extension properly. Should I update it manually somehow?

**Comment by alexzub** [comment] 2016-12-21 06:51
@mimkorn I apologize for radio silence from our side. We're going through the last stages of QA for the release, but everything looks pretty stable so far.

Let's see if manual update resolves the issue for you for now.

Please use this package: http://mrf.su/3h0G1g19142G

Download it. Make sure to remove the Extension that is currently installed through Chrome Web Store and follow this process to install the one you downloaded:

1) Unzip it in a convenient for you place
2) Open chrome://extensions/
3) Activate Developer Mode in the top right corner (see reference: http://mrf.su/3h2c3y1e220J )
4) Click "Load Unpacked Extension"
5) Choose the folder you've just unpacked

This should add the plugin to the list.

Please let us know if you experience the same issue even with this newer version (v0.8.0)

Thanks!

**Comment by mimkorn** [comment] 2016-12-21 08:16
Hi, the hiccups seem to be resolved - formerly there was a checkbox count of which the number was increased by the number of children. Now there is no checkbox, if there are no actual checklists on the card and the number is not increased by number of children, if there is a checklist present.

However, what bothered me more before was that the "parent child" buttons and info on the card were sometimes not shown, or took forever to be shown. I am testing on a different computer at the moment, so I will post an update on how it worked on my computer, when I come home, however, at the moment, the extension is working good, but the buttons and related cards take around 5 seconds to show - which is quite long. Is this supposed to happen? Does it just take too long to load? Or is it a bug? 

edit:

I tried it on a different trello board and there the buttons and parent - child relationships load (almost) instantly (on average under a second). The problem seems to appear only in my main board (I would have troubles sharing that one). Maybe it is because the board is quite extensively used? My ids are around 2600, which means this is the number of cards that were created. Most of them are archived, but I have around 13 lists with altogether around 150 active cards on the board. Some of them have pictures on the cover, (which is probably not related). Can it be a problem with scaling?

**Comment by alexzub** [comment] 2016-12-21 16:20
@mimkorn Thanks – indeed, the relationships are supposed to load almost instantly. It can definitely get slower with bigger scale boards as the plugin has to go through every single card and gather "Children" checklists from all of them in order to create the structure, including the archived cards as they might also be parts of the relationships. I'm afraid there isn't an easy/quick solution to this and this is definitely a limitation of the plugin for large-scale boards. It might be resolved in future updates but I definitely can't give a timeline on that as it might require major plugin overhaul. One way of resolving this could be deleting unnecessary cards, only if it's feasible in your case, of course.

**Comment by mimkorn** [comment] 2016-12-21 16:24
@azmorf thanks for the info. 

edit: for anyone who has the same problem I found a workaround: 

You can copy your board which will create exactly the same board but will leave out the archived items - this speeds up the extension a lot. I believe I could just create a new board every year or so, so I can search in history.
Cons: 
- you lose parent child relationships from your current board.

**Comment by mikewaters** [comment] 2017-01-06 14:39
Having the same issue, using 0.7.7 with a new board (not a lot of archived cards).  I'll wait for the new release and update you.  It happens about every 10 seconds.

**Comment by alexzub** [comment] 2017-01-06 14:49
@mikewaters Thanks for your feedback!

Let's see if manual update resolves the issue for you for now.

Please use this package: https://github.com/handsomecode/trello-parent-child/releases/download/v0.8.0/handsome-trello-chrome-extension-0.8.0.zip

Download it. Make sure to remove the Extension that is currently installed through Chrome Web Store and follow this process to install the one you downloaded:

1. Unzip it in a convenient for you place
2. Open chrome://extensions/
3. Activate Developer Mode in the top right corner (see reference: http://mrf.su/3h2c3y1e220J )
4. Click "Load Unpacked Extension"
5. Choose the folder you've just unpacked

This should add the plugin to the list.

Please let me know if you experience the same issue even with this newer version (v0.8.0)

We're planning to get it officially released next week but are going through the final QA rounds now. Your feedback could definitely help us.

Thanks!

**Comment by mikewaters** [comment] 2017-01-06 16:31
It's all good with 0.8.  Thanks folks.

**Comment by alexzub** [comment] 2017-01-11 00:32
Fixed in v0.8.0: https://chrome.google.com/webstore/detail/parentchild-management-fo/flnpbgmiploomjgagfbcjlikpiehclld

**Closed as completed by alexzub** 2017-01-11 00:32 UTC
Labels: bug
