### ISSUE TITLE
BUG: Parent/child buttons only appear after cards have been archived in Chrome 53

### ISSUE THREAD

**Issue by TobiasSkovgaardJepsen** [handsomecode/trello-parent-child#33] opened 2017-07-03 19:44 UTC
Parent/child buttons do not appear before a card has been archived. The buttons remain after being sent back to the board, but no existing cards can be set as parent or child. In addition, the buttons disappear after the card is moved in a list or to a different list.

Chrome Version 53.0.2785.143 (64-bit)

**Comment by guygadebois** [comment] 2017-07-06 15:48
Duplicate of https://github.com/handsomecode/trello-parent-child/issues/32
This be fixed now since this pr: https://github.com/handsomecode/trello-parent-child/commit/cecc2e60f76606df53ff5c849628858e143d5e8f

**Comment by alexzub** [comment] 2017-07-06 16:47
@TobiasSJ we've pushed the update v0.8.1 live in Chrome Store, and you should get the update within a few hours. The update fixes this issue.

**Closed as completed by alexzub** 2017-07-06 16:47 UTC
