### ISSUE TITLE
Buttons and lists of relations disappeared and are not shown anymore

### ISSUE THREAD

**Issue by mimkorn** [handsomecode/trello-parent-child#31] opened 2017-06-27 19:00 UTC
Hi, 

today when I sat to my trello board, the extension stopped working. Tried reinstalling, did not help. 

Might not sure if it should, but it does not appear to have a process in Chrome's Task Explorer.

I thought it migt be too many cards on the board, but it does not work even on fresh new ones.

Is this extension still working for everyone?

**Comment by alexzub** [comment] 2017-07-05 02:52
Closed as a duplicate of https://github.com/handsomecode/trello-parent-child/issues/32

**Closed as completed by alexzub** 2017-07-05 02:52 UTC
